version: "3.8"

services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin_user
      - MONGO_INITDB_ROOT_PASSWORD=admin_pass
      - MONGO_INITDB_DATABASE=database
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
    driver: local
